apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server-settings.yaml
  - server-adminlist.yaml
  - sealed-secret.yaml
  - mod-list.yaml
  - sealed-secret-mod-credentials.yaml
