apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: factorio-mod-credentials
  namespace: factorio
spec:
  encryptedData:
    username: AgBH0swpp3pVVaICA9fzt3ygAbpbSk/R+fqyFyv/sF6ROyicYArqY57mq5HbFr0SiLfiHvAZPizmkxPlfVf6bXaYqEzPjo7bSoaWxLkcLKefJYq8fkXSS9baN6Gdj2SuQNSU8vKisAVAD5VsL2XgE9IzzrmEcAkosL6tjDCdg5vBR5r9HoFdqG1Oe9Pzi4G0UG4+5a6XzcGNqcrVDocCYdrws9KzyDZF+Ctgi1Ovvj95m5HbAwqva3poByFQQfhps9HZhNWyYsoQi7LJEOTdzySAWYOdv1JeVwZZbRMGSnxtCPXRgrb6wz+jEzhuPR6cCQgarZ2hrOXu7Jvr8sFLNyr9t6HHhuUqdEDrU+3OQl4w43xxLt1vIeB7GbChUNbj1mQGMaxWO1K18UiWCP06XqJjwQeB2Gnh6WoR4t2RumYqbxo1I8Okzs4D0VZfy/T2V4PND71BeDhyXtyz3VmzrRBxsGDBBuxnFqfz25J7GDJVs/NdA+m9brrpio/jfCyXRyZZMxvoYOs5uouPSVzuuHLLO5/fiWagVd24k1UQEK/vt+Gu7+27eVS6dn9ty6ND48BQM+elpn/9AH2gK/Lp3OfAi9hL/qhuKpnlLMIw+aPfuezN+ohKHMS7tZQIoEoMVPP2tKjy1vSiVG4ac8NuwaUgiMCGo4V7NbueeOekF/Av3ExXJcJFQ6nEsI9u/aS1OHeyfYLsjHM=
    token: AgCgEKLyP/ymcY7TQyVmiQXNblFp9CO/qsjnQeJTitjWcYe7NJk/OYLhhy4LhEnBnxfPbvMfh3vZ2J8eh5TYni4Y9hCGh24zTBa5zstDEC3SpNtlao5BIar2EE5vtNlDyUCww/g7H95GAvpgEDzPZXg/OvnzysA2Qf8iiKy4cXH07ej4/V/x9UKxCCAurhZfAc5EeacfS2t2AoQ9hgqdvE4W4EaXM6z/jpfTsXzxmgomBwGk1vLn53Q3BH6lu5oHaZXV1wvltevgcBaH7GF4ywEjmmKKWbi9I+SEMKVpLhF2Cbc3MmzfVmyYQK3Pfq27qMSUY4H2uq125k9vaa8af/kPBEPZ5YFoYKcJ5Ta/MeK2nK2Q6HqksMuWisSfSNPxa8nXQFqx0DwSd6sOfogXSzanB/FrsKOxEvNTdTO7fGKJCgFg7rQVufAL4REbRP8qcCQatCIbA5kilsp4artCs49WsP4RWRkeWw5eCMclYYj9PvqFtSjVyRWCILuTGGwdjnbqF9hyyCDABB9XeXRYrh6z01Xe3M+GLPVXDD/N65J53B455jcvwyXKcTMj6e1sOg9/mNb4eNN97kNEDKtV6IBqEKIbS/9wvwdnNh5wNlF6gGvWxUWqmD+tDBlYCPu7Yd+DQghTGDStN74KXNGXdIy7zR82irmGRZ6o8ISaUMyPPcC69We9wpKauQE6+rXXLX+rxTqXibqZfkiZKQEBRQ+9EQ5aUmJqZ/P+QP9OvTE=
  template:
    metadata:
      name: factorio-mod-credentials
      namespace: factorio
    type: Opaque
