apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: factorio-mod-credentials
  namespace: factorio
spec:
  encryptedData:
    username: AgAzhFzaF4uLySI5I8D5m3jLibISjSkdkTMHWhc8XqnzAtvawq/cait5uEooX+OmBI5IGjGHzMxDibHTv6XHIprC6jPMIobCL70W2QtCt8t6oPk5xYAZUBffx442Zv9zH152fSEqHh8l0BgpF7u9HH8qm+gPHrExNYRn4Xp3olfY8ExstHuxohE53tRgdl4RKU6JfZA4dvn0O7LbX9vhDUDSAzlAi8sLjOjI0T2wMWkDBnuMYRwtAPdp2mldXXR8ij9dM2gHLMeSsJos96/KEbzwUs6wxflKEIVvcFlYuPYF3mSFBkNAhLaNb7GZvQRDYnwTI38Q/hR07hwETTkDWyFyweSpo6idu6yY1BnhJofiAgdqo967WoxY26yzAUqWJW8UpsPuX3aLFF50LPInhIm1aDRuiZYhFLykERzpmtlvoB5rk73t2waiZW/s3rKiU+Lsmd8zQ5ZFqaNvDG7CdIVLByW18MK9P/H8yuOLW0c039nGt6fsU+n+UY3TfOSd723ZZCMK9oLV/LJuqIbXwN8dbPiF2l60f6SH6T7peKPX/s0GJ+m3YulLVpzafsSUjlHXukxyEryGU+XyoqZ+qMf0arwiG09pMJoesxNdINBWqDyn9tWPRYOFTkx3BTc9DSHXYRsjbbjy3L9feDIIAXq4JcbyBKPAo7JER08YahX5styjZH5Jv4SGmmN3eU3WPRL2SmQGS9k=
    token: AgCL3FX8ITGamMzo58N0VmufYvF2Zn3A7F93w7Ex5dcc3f9hz3t725bU1S7I2F6L55aeFIcFMzUBWQhUbyJFB5Knqc1wzGh58qdT2yf9wx1qKugGYnkkAriPPVeoBdOzU5MZKKBGtVrObhCuY1KhEz2ow96QDL3Vo19+cYtmqGErwEj+1yHsIIK+JDhGogTUn6A8yqRrecrIzMP/wAs4BbaWVti+o1MeSXimtdxX1WzeQu+3Dr7TQjoh4Z7IPDRJZuFC9gVv28MvLWMvEVql8bZiPxCuz6g2p3cvX2iV6YMZZ9qEiN6mivCRRz1xpolelKxaUBymVqR372PTZphSeAAd2Kv63vzsCyKh3GYbvktLQYF3C5UiKjvwsw8LoubYLO2lvDOd83OrFLMx0+KfapuKV/enY7rZLMdNKYQae4OT1Ar3yAA98tH97jTHX3vj8IW15keUU5dOpkQ6gAJIl/DjTr+KJxfUToJwhhYOT9BX/db25SF1thrBXXZWNzZ3iWRYubCfbSG5Y1fZ+lcLKRkVxfWNygmv8D3QSoyBy7447fA18HLZFWs8RfCbV3vEDnytIakZoRTx3Nrpwy3JuRXAEIxYoQAz5RXihdpV97sNLRXyseV+m7+3JmWei4qvX+vJqwZ4qnL/ngb+uhRqHoerumlrxOV/rmUS1iVGok42Q/yoydrbq4BEZKZMkXuxObLQyVrxGimkG2vUUKYSiZqyVKRB60YohBzhAwDWPCg=
  template:
    metadata:
      name: factorio-mod-credentials
      namespace: factorio
    type: Opaque
