apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: factorio-game-password
  namespace: factorio
spec:
  encryptedData:
    game-password: AgBCd6LJeyrP1YScDKd1SYtdDKZHYEQbeT3rmXIP3hH9rcfdzQc/eGjAI2h6QpV9O07tU0HuSZIzhFEY6WJSc4WatD9lWcvdCGU9YgDOLIBYQWjjSkrNrGuTiuS1uz/ugK2e5m7foRfJkpLXuxFTkL69ZQMQuDxHtfSVDW1uD39Ra7tqcjhiYx6jGOZoyVtz6v29eqaSNk0OZTPe8nDSh6gV4KTKVBvRHqRFoWtEnJOmXJjtaPij7ek51//GwrjCB39cwFYlgutie9jRTBfKWgoHUFyiWswMfckSOdMR9giGum6gCuMyhQ2lpLFPpWIfT+tA9O3P+tZKdoL5sIhI8meJgYaP0nTpAPBxClb4M2dt1hA9f3SDVDq39BXpEwSNGUzGefbUzI9wgI/pOer7RMfrd7IcuuTyyC9rVPSknDuDVD4NZqIA8vXuPp/o9Al4EcIS8vjsMHU5pYx10CJU/wlmg1QIH1jly8kwE66edQDmlquUIforkZKvKjEUzQ9LpYPZiINswLNc+uzt+pSw9b7x8aJaDHLvLghcK+XAEcfGAS2/axFDebcdaamfBxORbi0qSxryv2zgCKhQ5DrsCXNXVDeL+1wM/hzayU9IDn4FhGjOSwDtemEkF91tsiEUWqYAHF1axoc1MbrU3P0cUOgf+7Ww0mSQFTPBVvyptFhBGikH7BwEs6o/uXAxCqiay6gh22sY3FpgoLhLn8Tg/Yoqv6CE2hvMkbUhRg==
  template:
    metadata:
      name: factorio-game-password
      namespace: factorio
    type: Opaque
