apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: factorio-mod-credentials
  namespace: factorio
spec:
  encryptedData:
    username: AgBmt07e4PrzyHz2k/clY5LHi6zElAZmFn45xI9Kkjp6wyBdvHBD+zaDC7e7OYS8iLbh9TGy0eyaMF5K1n6r64vm/UJzKw9+NIS2a4nzXJLtUto6L1kXYtFA3OEjJMytqcW6GLpZOyDA/QlD1GVeskW42zTS6V61k1CeQXJ9CAs/VAzAaPlbUMYqxpfIt6lK99oPdk+79JKrrrQt/tG/Bu7RzeOdBgpMYz1mNIqAKKcEBhAAGm2F36J3GPiFzW5CscNTPwmE7RCc09D7WaqHrQonjasDVR8IIVtfdrDNSrSzhihZEWOj2fiTtq4K7CwTsaD+oclCOEDIbN7QxrThfZXUDd7Q+ZPYWwnO4q+STya5JkTa6TCLbqx83PHzFTJET7mjYtu9CbzkqFUpTtdHR0yYXqYF/FhJ6KV9u0NcAXVfjVoag3DZks0FeCyfXG1lgUkHsGUhADtPjG7dKQrDBA4vIJmQ/RW3drCFkE5TG0jodDADw2QX7APOWe0t+5grWGpKUpqfJxzOgjsXUV3HljGGo2SMZpH8R9xF5lQcv8cI9RFiUYKaQJ3V7GV3sAYTlg5TQqxYnG7sVXhVhCBlKri4CvI2vGOew3G1j6xKYcZ9CLv1ujV6/SGB2+6c/irJnxQ4agOMfzZC3yBm5vyp1pfHKtILjy9YQVVPa5gHlurI1LLUPuy2TF8LTiIungSGOqCZXIW0ius=
    token: AgB19PEqeGpaD8+D1peLtcM7Fc3W1VknRppxBOhTIUReP5kKKMvFKUgwV+5DdSj5qU83eh5vI7zOKyuJhYaBqGnZMXYo7OjW/LWK8oCHb+lz+e5V0c8hyjxLtg3BMQFO7dg1BoQEzvMChIq6I7iA6KOscAUNnxFcrZQFXdEXcm5KvMlaxQE4etbAbxX3ew2GnKfHJtSYAf6Ogcd4XsD5NzIto+56wqdUMi5oU/9TafSmp9O3fcrXqU+yOemPyJ6Yovdj00XxC+meAexpcPZlG41tPR5kKcE2/DHpX7qApoxavdlIlwMsjAzdEqRJ8LhjO4ct6+VpJtxGS4fVYh3otuFNthojfapuBc4X9AVufgQhl9rT8kn64T/EV7ZQV4k3gZkbt7MkVvE7nio/kxMUN0bFyZmEvVWu3LVVKRGaLncq8pa4NAbuW5Bm4hU5B/Kr08HN9iTucsmhieaAE8ir4AiiTLlwb2GP/RbW+hvKjn0mxCBz3dA3wdBSfb+k0PaKVKSP818LlcyL39uhMFyI5C35j1ZqVFY0ArusbfC84suRKfhogS/kMxy/eL2G8soEewSFwWhgqd6oSUgWhNZdtFajBnLAwQqwI5OcAbH+t/IBkjxpvovjcqXxIlo+KEgvp3+ZhQVblQ8I4PiNHHKqA4/oTIRQG2U2EmF1SwvLlLzdqnrS4b8a0LryWeZGV0xp29ZMUgQYpJMc5JmK+MBKTQrhQsxEwEHI9BrYpZVUIjK2
  template:
    metadata:
      name: factorio-mod-credentials
      namespace: factorio
    type: Opaque
