apiVersion: v1
kind: ConfigMap
metadata:
  name: factorio-server-adminlist
  namespace: factorio
  labels:
    app.kubernetes.io/name: factorio
    app.kubernetes.io/component: config
data:
  server-adminlist.json: |
    [
      "daroot"
    ]
