apiVersion: v1
kind: Service
metadata:
  name: factorio-rcon
  namespace: factorio
  labels:
    app.kubernetes.io/name: factorio
    app.kubernetes.io/component: management
spec:
  type: ClusterIP
  selector:
    app: factorio
  ports:
    - name: rcon
      protocol: TCP
      port: 27015
      targetPort: 27015
