apiVersion: v1
kind: Service
metadata:
  name: factorio-game
  namespace: factorio
  labels:
    app.kubernetes.io/name: factorio
    app.kubernetes.io/component: game-server
spec:
  type: NodePort
  selector:
    app: factorio
  ports:
    - name: game
      protocol: UDP
      port: 34197
      targetPort: 34197
      nodePort: 34197
  externalTrafficPolicy: Cluster
